import subprocess
import os
import datetime

def get_git_info():
    try:
        # Get short hash
        hash = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"]).decode("utf-8").strip()
        # Get branch name
        branch = subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]).decode("utf-8").strip()
        # Check for uncommitted changes
        dirty = subprocess.call(["git", "diff", "--quiet", "--exit-code"]) != 0
        
        return hash, branch, dirty
    except Exception as e:
        return "unknown", "unknown", True

def update_version_file():
    hash, branch, dirty = get_git_info()
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    dirty_str = "-DIRTY" if dirty else ""
    
    version_content = f"""# This file is automatically generated. Do not edit manually.
GIT_HASH = "{hash}"
GIT_BRANCH = "{branch}"
GIT_DIRTY = {dirty}
BUILD_DATE = "{timestamp}"
VERSION_STR = "{branch} @ {hash}{dirty_str} ({timestamp})"
"""
    
    file_path = os.path.join("roborio", "version.py")
    with open(file_path, "w") as f:
        f.write(version_content)
    
    print(f"Updated {file_path}: {branch} @ {hash}{dirty_str}")

if __name__ == "__main__":
    update_version_file()
